---
title: "Question 3"
author: "Robert Priolo"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#initial setup
rm(list=ls())
t.critical <- function(alpha, df, tail = "two") {
  if(tail == "two"){
    result <- qt(1-alpha/2  , df)
  } else if(tail == "right"){
    result <- qt(1-alpha  , df)
  } else if(tail=="left"){
    result <- qt(alpha  , df)
  }
  return(result)
}

#data
library(POE5Rdata)
data("vegas5")
attach(vegas5)

#Libraries
library(POE5Rdata)
library(dynlm) #for the `dynlm()` function
library(broom) #for `glance(`) and `tidy()`
library(lmtest) #bgtest()
library(stargazer) #stargazer()
library(knitr) #kable()
library(sandwich) #coeftest()
library(car) #deltamethod qqPlot()
library(forecast) #forecast()
library(olsrr) #ols_plot_resid_lev()

```

```{r}

model.lm<- lm(default~arm+refinance+lien2+term30+underwater+ltv+rate+amount+fico)

#visual
qqPlot(model.lm, id=list(n=3))

#Bonferroni test
outlierTest(model.lm)

#influence plots
influenceIndexPlot(model.lm, id=list(n=3),vars="Cook")
influenceIndexPlot(model.lm, id=list(n=3),vars="Studentized")
influenceIndexPlot(model.lm, id=list(n=3),vars="Bonf")
influenceIndexPlot(model.lm, id=list(n=3),vars="hat")
influencePlot(model.lm, id=list(n=3))

#avplots
avPlots(model.lm, id=list(n=3, method="mahal"))

#dfbeta
dfbetas(model.lm)
plot(dfbetas(model.lm)) 
plot(dfbetas(model.lm)[ ,c("arm", "refinance")]) 

#ols plots
ols_plot_resid_lev(model.lm)
ols_plot_dfbetas(model.lm)
ols_plot_dffits(model.lm)




```

