---
title: "Question 1"
author: "Robert Priolo"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#initial setup
rm(list=ls())
t.critical <- function(alpha, df, tail = "two") {
  if(tail == "two"){
    result <- qt(1-alpha/2  , df)
  } else if(tail == "right"){
    result <- qt(1-alpha  , df)
  } else if(tail=="left"){
    result <- qt(alpha  , df)
  }
  return(result)
}

#data
library(POE5Rdata)
data("vegas5")
attach(vegas5)

#Libraries
library(POE5Rdata)
library(dynlm) #for the `dynlm()` function
library(broom) #for `glance(`) and `tidy()`
library(lmtest) #bgtest()
library(stargazer) #stargazer()
library(knitr) #kable()
library(sandwich) #coeftest()
library(car) #deltamethod qqPlot()
library(forecast) #forecast()
library(olsrr) #ols_plot_resid_lev()
library(dplyr)
library(ggplot2)
library(corrplot)
```


```{r}
head(vegas5)

vegas5$default <- as.factor(vegas5$default)
vegas5$arm <- as.factor(vegas5$arm)
vegas5$refinance <- as.factor(vegas5$refinance)
vegas5$lien2 <- as.factor(vegas5$lien2)
vegas5$term30 <- as.factor(vegas5$term30)
vegas5$underwater <- as.factor(vegas5$underwater)
str(vegas5)

#1
summary(vegas5)


#histograms

fd  <-  function(x) {
  n=length(x)
  r=IQR(x)
  2*r/n^(1/3)
}

fd(amount < median(amount))

vegas5 %>% filter(amount < median(amount)) %>% ggplot(aes(x = amount)) +
  geom_histogram(binwidth = fd, colour = "black") +
  aes(y = stat(count)/sum(stat(count))) +
  scale_y_continuous(labels=scales::percent) +
  ylab("%") + facet_wrap(~refinance)

fd(amount > median(amount))
vegas5 %>% filter(amount > median(amount) & amount < 180) %>% ggplot(aes(x = amount)) +
  geom_histogram(binwidth = fd, colour = "black") +
  aes(y = stat(count)/sum(stat(count))) +
  scale_y_continuous(labels=scales::percent) +
  ylab("Frequency(%)") + facet_wrap(~refinance, 
                         labeller = labeller(refinance = c(`0`="not refinanced", 
                                                           `1`="refinanced"))) +
  theme_bw()

head(vegas5)
fd(ltv)
ggplot(vegas5) + 
  geom_histogram(aes(x = ltv), binwidth = fd, colour = "black") +
  aes(y = ..count../sum(count)) +
  scale_y_continuous(labels = scales::percent) +
  ylab("%") + xlab("Loan-to-Value")

fd(rate)

ggplot(vegas5) + 
  geom_histogram(aes(x = rate), binwidth = fd, colour = "black") +
  aes(y = ..count../sum(count)) +
  scale_y_continuous(labels = scales::percent) +
  ylab("Frequency (%)") + xlab("Rates (%)") + facet_grid(refinance~underwater, switch = "both",
                                         labeller = labeller(
                                           refinance = c(`0` = "not refinanced", 
                                                          `1`= "refinanced"), 
                                           underwater = c(`0` = "not underwater",
                                                          `1` = "underwater")
                                         )) + 
  theme_bw()

#correlation plot

anyNA(vegas5)
corrplot(cor(vegas5[,7:10]))


#boxplot
head(vegas5)
ggplot(vegas5,aes(x = default, y = ltv, 
                  colour = ltv)) +
  geom_boxplot() 

 ggplot(vegas5,aes(x = refinance, y = rate)) +
  geom_boxplot(aes(colour = lien2))
                    
 
 ggplot(vegas5,aes(x = lien2, y = fico)) +
   geom_boxplot(aes(colour = term30)) 

 
 ggplot(vegas5, aes(x = underwater, y = amount)) +
   geom_boxplot(aes(colour = lien2)) + facet_grid(refinance~term30)
 
 

 #scatterplot
scatterplotMatrix(vegas5[,7:10], col = "steelblue", 
                  ellipse = TRUE)

str(vegas5)
reg.mod <- lm(default~., data = vegas5)
summary(reg.mod)

coeftest(reg.mod, vcov. = hccm(reg.mod, type = "hc1"))
plot(reg.mod)

head(vegas5)
ggplot(vegas5 %>% filter(amount < 125), aes(x = amount, y = fico)) +
  geom_point() + geom_smooth()

```

